### ISSUE TITLE
Server crashes on startup neovim

### ISSUE THREAD

**Issue by gruvw** [olrtg/emmet-language-server#8]
Hello, I don't know if I am doing something wrong, but I can't figure out how to start this LSP server without it crashing.

Everything works perfectly with `emmet-ls` but when I start `emmet-language-server` I instantly get the error message `Client 1 quit with exit code 1 and signal 0`.

**Comment by gruvw** [comment]
Yes, please find my current config at https://github.com/gruvw/dotfiles/tree/main/nvim/.config/nvim

When using `"emmet_language_server"` instead of `"emmet_ls"` in https://github.com/gruvw/dotfiles/blob/bf369d4d6f71f49f3a85cf74a2ee0896807ea64a/nvim/.config/nvim/lua/plugins/lsp.lua#L72, I get the error message `Client 1 quit with exit code 1 and signal 0` and running `:LspInfo` shows that there are no LSP client attached to my current buffer (HTML).

**Comment by olrtg** [comment]
Hmm, that's weird 🤔 I'm testing it right now but everything works just fine. With and without lspconfig.

What about your node version? Did you check `:LspLog`? Are you sure `emmet-language-server` is in your path?

**Comment by olrtg** [comment]
Maybe try this?

```lua
require("mason-lspconfig").setup({
  automatic_installation = true,
  ensure_installed = {
    "pyright",
    "rust_analyzer",
    "marksman",
    "texlab",
    "lua_ls",
    "emmet_language_server",
  },
  handlers = {
    lsp.default_setup,
    lua_ls = function()
      require("lspconfig").lua_ls.setup(lsp.nvim_lua_ls())
    end,
    emmet_language_server = function()
      require("lspconfig").emmet_language_server.setup({})
    end,
  },
})
```

**Comment by gruvw** [comment]
Node version: `v12.22.9`

LspLog might be interesting:

```
[ERROR][2023-08-23 10:39:59] .../vim/lsp/rpc.lua:734	"rpc"	
"/home/gruvw/.local/share/nvim/mason/bin/emmet-language-server"	"stderr"	
"/home/gruvw/.local/share/nvim/mason/packages/emmet-language-server/node_modules/@olrtg/
emmet-language-server/node_modules/vscode-jsonrpc/lib/common/linkedMap.js:40\n        return 
this._head?.value;\n                          ^\n\nSyntaxError: Unexpected token '.'\n    at 
wrapSafe (internal/modules/cjs/loader.js:915:16)\n    at Module._compile 
(internal/modules/cjs/loader.js:963:27)\n    at Object.Module._extensions..js 
(internal/modules/cjs/loader.js:1027:10)\n    at Module.load 
(internal/modules/cjs/loader.js:863:32)\n    at Function.Module._load 
(internal/modules/cjs/loader.js:708:14)\n    at Module.require 
(internal/modules/cjs/loader.js:887:19)\n    at require 
(internal/modules/cjs/helpers.js:74:18)\n    at Object.<anonymous> 
(/home/gruvw/.local/share/nvim/mason/packages/emmet-language-server/node_modules/@olrtg/emmet-
language-server/node_modules/vscode-jsonrpc/lib/common/api.js:37:21)\n    at Module._compile
 (internal/modules/cjs/loader.js:999:30)\n    at Object.Module._extensions..js 
(internal/modules/cjs/loader.js:1027:10)\n"
```

Running the command alone exits with `error 1` and yields:
```
/home/gruvw/.local/share/nvim/mason/packages/emmet-language-server/node_modules/@olrtg/emmet-language-server/node_modules/vscode-jsonrpc/lib/common/linkedMap.js:40
        return this._head?.value;
                          ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/gruvw/.local/share/nvim/mason/packages/emmet-language-server/node_modules/@olrtg/emmet-language-server/node_modules/vscode-jsonrpc/lib/common/api.js:37:21)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

**Comment by olrtg** [comment]
Oh, yeah maybe you need to update 🤔 Try that and let me know! Never saw that error before. Try with the latest lts (v18) or if you don't want to go that far try with v14.

**Comment by gruvw** [comment]
Great, upgrading node to `v18.17.1` following https://askubuntu.com/questions/426750/how-can-i-update-my-nodejs-to-the-latest-version fixed the issue for me!

Thanks a lot :)
